### ISSUE TITLE
CA bundle

### ISSUE THREAD

**Issue by hrach** [uestla/ReCaptchaControl#12]
Enabling ca verification (👍) made this component not working on default Windows setup. I suggest using composer/ca-bundle.

**Comment by hrach** [comment]
Or, let us somehow configurethe ca path through extension.

**Comment by uestla** [comment]
Shouldn't PHP ca path configuration on your Windows setup be enough? It was in my case...

**Comment by hrach** [comment]
Yes, that would probably work ok, but the reality is, that it's too difficult to set up/update, etc.

**Comment by uestla** [comment]
OK, but from what I see since you are on Windows and don't have your CA path configured on the PHP site - [all these paths]() are irrelevant for you and the most important line [is this one](), right? Is that a hardcoded certificate?

Are you running Windows on your development machine or on production?

Do you think it is common to have multiple CA paths in one environment so that this 3rd party dependency is necessary?

And if you want to manually configure the CA path just in this extension, why not set in directly in PHP and have it work in all other applications?

**Comment by hrach** [comment]
> So would it be OK to add the ca-bundle just for dev?

I cannot imagine how would you make this happend. Other solution is to let this be configurable, I will handle it myself.

**Comment by uestla** [comment]
@hrach I'm sorry, but I don't see how it would be easier to configure the CA path for one package (this one) than to configure it globally on whole system (Windows).

Do you have any suggestion how this configuration could look like / could you provide a pull request for this functionality?

**Comment by hrach** [comment]
In the end, I changed my mind. Thanks!

**Comment by uestla** [comment]
@hrach I just wanted to ask you for a favor (even though this is already closed).

I just added a layer for sending HTTP requests which adds also the possibility to modify the default cURL request options:

https://github.com/uestla/ReCaptchaControl#curlrequester

Could you please take a time and test it? If it's all OK I would release new major version.

Thanks!
